[project]
<<<<<<< HEAD
name = "fast-api-lap"
=======
name = "week9"
>>>>>>> 24e134270b137fbb3050eae32f6969ceeb0a14af
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
<<<<<<< HEAD
    "fastapi>=0.128.2",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.40.0",
=======
    "pyside6>=6.10.1",
>>>>>>> 24e134270b137fbb3050eae32f6969ceeb0a14af
]
